Use gom

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -46,30 +46,14 @@ fi
 plat=$(uname|tr A-Z a-z)-$arch
 
 # Python
-venv=$cache/venv
-mkdir -p $cache/pip
-python=python2.7
-PATH=$buildpack/$plat/bin:$venv/bin:$PATH
+PATH=$buildpack/$plat/bin:$PATH
 
-virtualenv() {
-    python "$buildpack/vendor/virtualenv-1.7/virtualenv.py" "$@"
-}
-
-if test -f $build/Godeps
+if test -f $build/Gomfile
 then
-    name=$(<$build/Godeps jq -r .ImportPath)
-    ver=$(<$build/Godeps jq -r .GoVersion)
-elif test -d $build/Godeps
-then
-    name=$(<$build/Godeps/Godeps.json jq -r .ImportPath)
-    ver=$(<$build/Godeps/Godeps.json jq -r .GoVersion)
-elif test -f $build/.godir
-then
-    name=$(cat $build/.godir)
+    name=app
     ver=go${GOVERSION:-1.3}
 else
-    echo >&2 " !     A .godir is required. For instructions:"
-    echo >&2 " !     http://mmcgrana.github.io/2012/09/getting-started-with-go-on-heroku"
+    echo >&2 " !     A Gomfile is required."
     exit 1
 fi
 
@@ -102,28 +86,6 @@ GOROOT=$cache/$ver/go export GOROOT
 GOPATH=$build/.heroku/g export GOPATH
 PATH=$GOROOT/bin:$PATH
 
-
-if ! (test -d $build/Godeps || (which hg >/dev/null && which bzr >/dev/null))
-then
-    echo
-    echo "       Tired of waiting for bzr and hg?"
-    echo "       Try github.com/kr/godep for faster deploys."
-    echo
-
-    echo -n "       Installing Virtualenv..."
-    virtualenv --python $python --distribute --never-download --prompt='(venv) ' $venv > /dev/null 2>&1
-    . $venv/bin/activate > /dev/null 2>&1
-    echo " done"
-
-    echo -n "       Installing Mercurial..."
-    pip install mercurial > /dev/null 2>&1
-    echo " done"
-
-    echo -n "       Installing Bazaar..."
-    pip install bzr > /dev/null 2>&1
-    echo " done"
-fi
-
 p=$GOPATH/src/$name
 mkdir -p $p
 cp -R $build/* $p
@@ -144,14 +106,12 @@ fi
 
 unset GIT_DIR # unset git dir or it will mess with goinstall
 cd $p
-if test -e $build/Godeps
-then
-    echo "-----> Running: godep go install -tags heroku ./..."
-    godep go install -tags heroku ./...
-else
-    echo "-----> Running: go get -tags heroku ./..."
-    go get -tags heroku ./...
-fi
+echo "-----> Running: gom install"
+gom install
+echo "-----> Running: gom build"
+gom build
+echo "-----> Running: copy $name to $GOBIN"
+cp $name $GOBIN
 
 rm -rf $build/.heroku
 
